image: docker:latest
services:
  - docker:dind

build-job:
  stage: build
  script:
    - docker build -t lchanif/people-api-frontend .
    - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
    - docker push lchanif/people-api-frontend
  tags:
    - build_docker
    
test-job:
  stage: test
  script:
    - docker run -d lchanif/people-api-frontend:latest -name frontend
  tags:
    - build_docker

deploy:
  stage: deploy
  script:
    - sh upgradeRancher.sh
  tags:
    - build_docker
